#!/usr/bin/env python3
# --------------------( LICENSE                            )--------------------
# Copyright (c) 2014-2026 Beartype authors.
# See "LICENSE" for further details.

'''
**Beartype decorator** :pep:`484` **type hint code generation** unit tests.

This submodule unit tests the :func:`beartype.beartype` decorator with respect
to :pep:`484`-specific type-checking code dynamically generated by the
:mod:`beartype._decor._nontype._wrap.wrapmain` submodule.
'''

# ....................{ IMPORTS                            }....................
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# WARNING: To raise human-readable test errors, avoid importing from
# package-specific submodules at module scope.
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
from beartype_test._util.mark.pytmark import ignore_warnings
from beartype_test._util.mark.pytskip import skip

# ....................{ TESTS ~ decorator                  }....................
# Prevent pytest from capturing and displaying all expected non-fatal
# beartype-specific warnings emitted by the @beartype decorator below. Urgh!
#FIXME: Remove when worky, obviously. *sigh*
@skip('Currently brokey.')
@ignore_warnings(DeprecationWarning)
def test_beartype_pep484_ref_str(iter_hints_piths_meta) -> None:
    '''
    Test the :func:`beartype.beartype` decorator with respect to type-checking
    code dynamically generated by the
    :mod:`beartype._decor._nontype._wrap.wrapmain` submodule for
    :func:`beartype.beartype`-decorated callables annotated by one or more
    :pep:`484`-compliant stringified forward reference type hints referring to
    other arbitrary type hints supported by :mod:`beartype`.

    This is the core unit test validating decorator functionality from the end
    user perspective -- the only perspective that matters, in the end.
    Unsurprisingly, this test is mildly more involved than most. *Whatevah.*

    Parameters
    ----------
    iter_hints_piths_meta : Callable[[], Iterable[beartype_test.a00_unit.data.hint.metadata.data_hintpithmeta.HintPithMetadata]]
        Factory function creating and returning a generator iteratively yielding
        ``HintPithMetadata`` instances, each describing a sample type hint
        exercising an edge case in the :mod:`beartype` codebase paired with a
        related object either satisfying or violating that hint.
    '''

    # ....................{ IMPORTS                        }....................
    # Defer test-specific imports.
    from beartype import beartype
    from beartype.roar import BeartypeCallHintViolation
    from beartype._util.text.utiltextansi import strip_str_ansi
    from beartype_test.a00_unit.data.hint.metadata.data_hintpithmeta import (
        PithUnsatisfiedMetadata)
    from beartype_test._util.error.pyterrraise import raises_uncached
    from re import search
    # from warnings import simplefilter

    # ....................{ SETUP                          }....................
    # Force pytest to temporarily allow deprecation warnings to be caught by the
    # warns() context manager for the duration of this test. By default, pytest
    # simply "passes through" all deprecation warnings for subsequent reporting
    # if tests otherwise successfully pass. Deprecation warnings include:
    # * "DeprecationWarning".
    # * "FutureWarning".
    # * "PendingDeprecationWarning".
    # simplefilter('always')

    # ....................{ ASSERTS                        }....................
    # For each predefined type hint and associated metadata...
    for hint_pith_meta in iter_hints_piths_meta():
        # ....................{ LOCALS                     }....................
        # Metadata describing this hint.
        hint_meta = hint_pith_meta.hint_meta

        # Object to type-check against this hint.
        pith = hint_pith_meta.pith

        # Metadata describing this pith.
        pith_meta = hint_pith_meta.pith_meta
        # print(f'Type-checking PEP type hint {repr(hint_meta.hint)}...')

        # Beartype decorator configured specifically for this hint.
        beartype_confed = beartype(conf=hint_meta.conf)

        # ....................{ CALLABLES                  }....................
        @beartype_confed
        def func(arg: 'hint') -> 'hint':
            '''
            :func:`beartype.beartype`-decorated function both accepting a single
            parameter and returning a value annotated by :pep:`484`-compliant
            stringified relative forward reference type hint referring to this
            hint, whose implementation reduces to the identity function.
            '''

            return arg

        # Type hint to be type-checked, intentionally localized *AFTER* defining
        # the above callable annotated by PEP 484-compliant stringified relative
        # forward reference type hints referring to this hint. If this hint were
        # instead define *BEFORE* defining that callable, the @beartype
        # decorator decorating that callable would simply resolve those relative
        # forward reference type hints at decoration time to this hint. Doing so
        # would prevent this unit test from validating any of the more esoteric
        # beartype machinery required to type-check references to arbitrary
        # non-type hints at late call time (rather than early decoration time).
        hint = hint_meta.hint

        # ....................{ VIOLATE                    }....................
        #FIXME: Reduce DRY violations between this and the sibling
        #test_beartype() test by:
        #* Defining a new "beartype_test.a00_data.hint.metadata.pith"
        #  subpackage.
        #* Splitting up the existing
        #  "beartype_test.a00_data.hint.metadata.data_hintpithmeta" submodule
        #  into these new submodules:
        #  * "beartype_test.a00_data.hint.metadata.pith.data_pithmeta",
        #    defining *ONLY* the "PithSatisfiedMetadata" and
        #    "PithUnsatisfiedMetadata" dataclasses.
        #  * "beartype_test.a00_data.hint.metadata.pith.data_hintmeta",
        #    defining *ONLY* the "HintNonpepMetadata" and "HintPepMetadata"
        #    dataclasses.
        #  * "beartype_test.a00_data.hint.metadata.pith.data_hintpithmeta",
        #    defining *ONLY* the "HintPithMetadata" dataclass.
        #* Define a new HintPithMetadata.check_func() method with signature:
        #    def check_func(self, func: Callable[[object], object]) -> None:
        #* Copy-paste everything below into the body of that method.
        #* Call that method both here and in the sibling test_beartype() test.

        # If this pith violates this hint...
        if isinstance(pith_meta, PithUnsatisfiedMetadata):
            # ....................{ EXCEPTION ~ type       }....................
            # Assert this wrapper function raises the expected exception when
            # type-checking this pith against this hint.
            with raises_uncached(BeartypeCallHintViolation) as exception_info:
                func(pith)

            # Exception captured by the prior call to this wrapper function.
            exception = exception_info.value

            # Exception type localized for debuggability. Sadly, the
            # pytest.ExceptionInfo.__repr__() dunder method fails to usefully
            # describe its exception metadata.
            exception_type = exception_info.type

            # Assert this exception metadata describes the expected exception
            # as a sanity check against upstream pytest issues and/or issues
            # with our raises_uncached() context manager.
            assert issubclass(exception_type, BeartypeCallHintViolation)

            # Assert this exception to be public rather than private. The
            # @beartype decorator should *NEVER* raise a private exception.
            assert exception_type.__name__[0] != '_'

            # ....................{ EXCEPTION ~ culprits   }....................
            # Tuple of the culprits responsible for this exception, localized to
            # avoid inefficiently recomputing these culprits on each access.
            exception_culprits = exception.culprits

            # Assert that this tuple both exists *AND* is non-empty.
            assert isinstance(exception_culprits, tuple)
            assert exception_culprits

            # First culprit, which *SHOULD* be either:
            # * If this pith can be weakly referenced, this pith.
            # * Else, this pith *CANNOT* be weakly referenced. In this case,
            #   fallback to the truncated representation of this pith.
            culprit_pith = exception_culprits[0]

            # If the first culprit is a string...
            if isinstance(culprit_pith, str):
                # Assert that this string is non-empty.
                assert culprit_pith
            # Else, the first culprit is *NOT* a string. In this case...
            else:
                # Assert that the first culprit is this pith.
                assert culprit_pith is pith

                # If two or more culprits were responsible...
                if len(exception_culprits) >= 2:
                    # For each culprit following the first...
                    for culprit_nonpith in exception_culprits[1:]:
                        # Assert that this subsequent culprit is *NOT* the pith.
                        assert culprit_nonpith is not pith

            # ....................{ EXCEPTION ~ message    }....................
            # Exception message raised by this wrapper function.
            exception_str = strip_str_ansi(str(exception))
            # print('exception message: {}'.format(exception_str))

            # Assert this exception message is prefixed by a substring
            # identifying the decorated callable with a human-readable label.
            assert not exception_str.startswith('Function ')

            # Assert that iterables of uncompiled regular expression expected
            # to match and *NOT* match this message are *NOT* strings, as
            # commonly occurs when accidentally omitting a trailing comma in
            # tuples containing only one string: e.g.,
            # * "('This is a tuple, yo.',)" is a 1-tuple containing one string.
            # * "('This is a string, bro.')" is a string *NOT* contained in a
            #   1-tuple.
            assert not isinstance(
                pith_meta.exception_str_match_regexes, str)
            assert not isinstance(
                pith_meta.exception_str_not_match_regexes, str)

            # For each uncompiled regular expression expected to match this
            # message, assert this expression actually does so.
            #
            # Note that the re.search() rather than re.match() function is
            # called. The latter is rooted at the start of the string and thus
            # *ONLY* matches prefixes, while the former is *NOT* rooted at any
            # string position and thus matches arbitrary substrings as desired.
            for exception_str_match_regex in (
                pith_meta.exception_str_match_regexes):
                assert search(
                    exception_str_match_regex, exception_str) is not None

            # For each uncompiled regular expression expected to *NOT* match
            # this message, assert this expression actually does so.
            for exception_str_not_match_regex in (
                pith_meta.exception_str_not_match_regexes):
                assert search(
                    exception_str_not_match_regex, exception_str) is None
        # ....................{ SATISFY                    }....................
        # Else, this pith satisfies this hint. In this case...
        else:
            # Assert this wrapper function successfully type-checks this pith
            # against this hint *WITHOUT* modifying this pith.
            assert func(pith) is pith
