# --------------------( LICENSE                           )--------------------
# Copyright (c) 2014-2022 Beartype authors.
# See "LICENSE" for further details.
#
# --------------------( SYNOPSIS                          )--------------------
# Project-wide Read The Docs (RTD) configuration.

# ....................{ METADATA                          }....................
# RTD configuration scheme version this file complies with.
version: 2

# ....................{ INSTALLATION                      }....................
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc-rtd

  # Permit Read The Docs (RTD) to reuse Python packages installed by its
  # system package manager, which mostly means the standard scientific stack.
  system_packages: true

# ....................{ SPHINX                            }....................
#FIXME: Uncomment the following *AFTER* eliminating all warnings across our
#documentation. Since we have yet to do so, this remains commented. It is sad.
# sphinx:
#   # For safety, convert non-fatal Sphinx warnings into fatal errors.
#   fail_on_warning: true
