# --------------------( LICENSE                            )--------------------
# Copyright (c) 2014-2025 Beartype authors.
# See "LICENSE" for further details.
#
# --------------------( SYNOPSIS                           )--------------------
# Project-wide MkDocs configuration, applied to all invocations of the MkDocs
# documentation generator within this project -- including both by directly
# running the external "mkdocs" command locally and by indirectly running that
# command remotely from GitHub Actions-based documentation workflows.
#
# --------------------( COMMANDS                           )--------------------
# Commonly used MkDocs commands include:
#     # Add a default MkDocs documentation tree to the current project:
#     cd ~/py/${PROJECT_NAME}
#     mkdocs new .
#
#     # Locally test the current MkDocs documentation tree:
#     mkdocs serve
#
#     # Remotely push to the GitHub Pages-hosted Project Site:
#     mkdocs gh-deploy

# ....................{ CORE                                }...................
#FIXME: Define all remaining relevant configuration options specified here:
#    https://www.mkdocs.org/user-guide/configuration

# Human-readable name of the static site generated by MkDocs.
site_name: Beartype

# Human-readable description of this site, injected as a proper HTML-compliant
# "<meta...>" tag into the HTML header of each site page.
site_description: >-
  Unbearably fast near-real-time hybrid runtime-static type-checking in pure
  Python.

# Human-readable name(s) of the author(s) of this site.
site_author: "Beartype"

# Human-readable copyright line, typically injected into each page by the
# third-party theme configured below.
copyright: "Copyright (c) 2014-2025 Beartype authors."

# URL of the repository documented by this site. 
repo_url: https://github.com/beartype/beartype

# ....................{ PATHS                               }...................
# Relative or absolute dirname of the top-level MkDocs-specific input
# subdirectory documenting this repository with MkDocs-specific markdown.
docs_dir: 'docs'

# Relative or absolute dirname of the top-level MkDocs-specific output
# subdirectory storing all web-compliant files (e.g., HTML, CSS, JavaScript)
# generated by the "mkdocs build" subcommand required to render this site.
#
# Note that this dirname intentionally corresponds to the Jekyll-specific
# output dirname leveraged by our ".github/workflows/python_docs.yml" workflow.
site_dir: '_site'

# ....................{ PLUGINS                             }...................
# Both first- and third-party MkDocs plugins currently employed by this project.
plugins:
  # ....................{ PLUGINS ~ builtin                 }...................
  # First-party MkDocs plugins bundled with Mkdocs itself.

  # Enable the builtin search bar, which the Material theme seamlessly
  # integrates with. See also:
  #     https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search
  - search

  # ....................{ PLUGINS ~ third-party             }...................
  # Third-party MkDocs plugins external to Mkdocs itself.

  # Automatically generate API reference documentation from Python docstrings
  # embedded inside the Python package defined by this project. See also:
  #     https://github.com/mkdocstrings/mkdocstrings
  - mkdocstrings:
      handlers:
        python:
          # List of all inventories (i.e., external URLs to Sphinx-formatted
          # inventory files listing all Python attributes provided by the APIs
          # hosted at those URLs). Third-party attributes provided by an
          # inventory listed below will be implicitly linked to; all other
          # third-party attributes will remain unlinked.
          inventories:
            # Official inventory providing:
            # * All Python builtins.
            # * The standard Python library.
            - https://docs.python.org/3/objects.inv

          options:
            # Prefer NumpyDoc-style Python docstrings. By default, "mkdocstrings"
            # assumes Google-style Python docstrings.
            docstring_style: numpy

          # List of all dirnames relative to this configuration file under which
          # to discover documentation.
          paths:
            # The current working directory.
            - "."

# ....................{ THEME                               }...................
# Third-party MkDocs UI theme currently employed by this project.
theme:
  # Material of Mkdocs. The one. The only. See also:
  #     https://squidfunk.github.io/mkdocs-material
  name: material

  # Theme-specific features.
  features:
    # Enable search highlighting, dynamically displaying all occurrences of the
    # search term in each found document.
    - search.highlight

    # Enable search suggestions, dynamically displaying the likeliest completion
    # for the last word which can be accepted with the <Right> arrow key.
    - search.suggest

  # Theme-specific color scheme(s). See also:
  #     https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors
  palette:
    # Palette toggle for dark mode.
    #
    # Note that "slate" is Material's name for its default dark mode. *sigh*
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for light mode.
    #
    # Note that "default" is Material's name for its default light mode. I know.
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
