# 120 is too match, but ok, 88 - is ok
# 79 - is best, because of some people's broken eyes
# and vertical oriented monitotes (dangerous people).
line-length = 275
target-version = "py38"
include = [
    "beartype/*.py",
    "pyproject.toml",
    "ruff.toml",
]
exclude = []

[lint]
select = ["UP"]
extend-safe-fixes = [
    "TCH", # flake8-type-checking. TYPE_CHECKING support
    "UP",  # pyupgrade
]
extend-unsafe-fixes = [
    "F841",   # Checks for the presence of unused variables in function scopes.
]
preview = true

[format]
docstring-code-format = true
line-ending = "lf"           # Use `\n` line endings for all files
preview = true
quote-style = "preserve"  # Ideally replace this with "signale" or "double"

[lint.pyupgrade]
keep-runtime-typing = true

[lint.pycodestyle]
max-line-length = 275 

[lint.flake8-annotations]
allow-star-arg-any = true

[lint.per-file-ignores]
"!**/beartype_test/*" = ["PT017"] # Checks for assert statements in except clauses.
"**/beartype_test/*" = ["RUF018"] # Checks for named assignment expressions (e.g., x := 0) in assert statements.
"beartype/claw/_ast/*.py"=["N802"] # Function name should be lowercase

[lint.flake8-type-checking]
exempt-modules = ["typing", "typing_extensions"]
runtime-evaluated-base-classes = []
runtime-evaluated-decorators = [
    "beartype.beartype",
]
strict = true

[lint.isort]
force-single-line = false
lines-after-imports = 1

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.flake8-quotes]
# Don't bother trying to avoid escapes.
avoid-escape = false
# docstring-quotes = "single"
# inline-quotes = "single"
# multiline-quotes = "single"
