#!/usr/bin/env python3
# --------------------( LICENSE                            )--------------------
# Copyright (c) 2014-2026 Beartype authors.
# See "LICENSE" for further details.

'''
Beartype **forward reference fake classes** (i.e., low-level class hierarchy
pretending to resolve otherwise unresolvable runtime-hostile forward references
through bald-faced trickery, casual deceit, and code prestidigitation the likes
of which no living Pythonista could countenance).

This private submodule is *not* intended for importation by downstream callers.
'''

# ....................{ TODO                               }....................
#FIXME: *UNIT TEST EVERYTHING* before we actually use this anywhere. Fairly
#hardcore subtle stuff going on here. *shrug*

# ....................{ IMPORTS                            }....................
from beartype._util.cache.utilcachecall import callable_cached
from beartype._util.cls.utilclsmake import make_type

# ....................{ PROXIERS                           }....................
@callable_cached
def proxy_hint_pep484_ref_str_nested(
    scope_name: str, hint_name: str) -> type['_BeartypeForwardRefFakeABC']:
    '''
    Create and return a new **forward reference fake proxy** (i.e., concrete
    :class:`._BeartypeForwardRefFakeABC` subclass) pretending to proxy calls to
    the :func:`isinstance` and :func:`issubclass` builtins when passed this
    proxy as their second parameters on behalf of the passed
    :pep:`484`-compliant stringified relative forward reference type hint
    presumably referring to a **nested type** (i.e., low-level class whose
    declaration is confined to the body of a previously called higher-level
    callable and thus inaccessible to the current call stack lacking a stack
    frame encapsulating that prior call).

    This type factory is memoized for efficiency.

    Motivation
    ----------
    Each type dynamically generated by this type factory is principally intended
    to proxy a :pep:`484`-compliant stringified forward reference type hint
    annotating a :func:`beartype.beartype`-decorated **nested callable** (i.e.,
    closure or nested function defined inside the body of another callable)
    presumably referring to such a nested type. Since that nested type is only
    locally defined and thus inaccessible to general-purpose call stack
    introspection, the naive approach to resolving forward references against
    that nested type would be to simply emit false positives by raising fatal
    exceptions, which is what :mod:`beartype` previously did. However
    well-intended, a runtime type-checker knowingly emitting false positives is
    no better than a static type-checker doing so. Any alternative is preferable
    to that. An equally naive (but less blatantly harmful) approach would be to
    simply emit false negatives by silently ignoring that nested type, which is
    what :mod:`beartype` next did. Assuming :mod:`beartype` can do better,
    unconditional false negatives are still unsatisfactory. Can :mod:`beartype`
    do better, though? :mod:`beartype` can.

    Consider the following minimal reproducible example (MRE), exhibiting
    Leycec's Last Theorem of Forward References:

    .. code-block:: python

       def closure_factory() -> tuple[Callable, type]:
           from beartype import beartype

           @beartype
           def closure(type_undefined: '_TypeUndefined') -> '_TypeUndefined':
               return type_undefined

           class _TypeUndefined(): pass
           return (closure, _TypeUndefined)

       closure, _TypeUndefined = closure_factory()
       closure_obj = _TypeUndefined()

       # The @beartype-decorated type-checking wrapper created and returned by
       # the above closure factory should silently accept a valid instance of
       # private type confined to the same closure, despite the declarotion of
       # this type no longer residing on the current call stack and thus being
       # inaccessible to runtime introspection by @beartype.
       assert closure(closure_obj) is closure_obj

       # This type-checking wrapper should loudly reject all other passed
       # objects as invalid by raising the expected type-checking violation.
       closure('Pretty sure a string isn't a "_TypeUndefined" object.')

    Leycec's Last Theorem of Forward References is thus: "Can a pure runtime
    type-checker both avoid false positives and minimize (but not entirely
    eliminate) false negatives by type-checking forward references referring to
    previously defined nested types inaccessible in the current scope?"

    Since this type factory exists, the answer is clearly: "Yes, but you're not
    gonna like it. No one's gonna like it. We don't like it. Actually, that's a
    lie. We like it. It's a clever kludge. We like clever kludges. Because you
    are reading this, so do you. Guess everyone that matters likes it, huh?"

    Here's how we roll this shadow madness. First, the fake proxy returned by
    this type factory shares the same passed classname and module name as that
    of that nested type proxied by this fake proxy. Next, when passed as the
    second parameter to either the :func:`isinstance` and :func:`issubclass`
    builtin, the metaclass of this fake proxy pretends to proxy that call to
    that nested type. How? By iteratively searching up the method-resolution
    order (MRO) of the object passed to that call for a transitive superclass of
    that object sharing the same classname and module name as that of this fake
    proxy. If such a superclass is found, that passed object is likelier to be
    an instance or subclass of the nested type referred to by the forward
    reference proxied by this fake proxy. The cautious reader should note the
    weasel word "likelier" doing a lot of heavy lifting here.

    Technically, this is merely an ad-hoc heuristic. It's trivial to concoct
    malicious (albeit thankfully unlikely) scenarios in which an object whose
    type shares the same classname as that of a forward reference is *not* an
    instance or subclass of the actual type referred to by that reference. It
    happens. It's also unlikely.

    Pragmatically, this ad-hoc heuristic has the beneficial side effect of
    dramatically reducing the likelihood of false negatives in this edge case
    (which is good) *without* any concomitant harmful side effect like emitting
    false positives (which is also good). In other words, this heuristic has
    entirely good effects and is thus preferable to our only alternative (which
    is doing nothing).

    Why is this heuristic guaranteed to *not* emit false positives? Assume this
    heuristic emitted false positives. Then this heuristic invites erroneous
    type-checking violations by returning :data:`False` when it should instead
    return :data:`True` for some fake proxy ``fake_proxy`` and user-defined
    object ``obj``, implying:

    .. code-block:: python

       fake_proxy.__name__ != obj.__class__.__name__

    However, this heuristic should instead return :data:`True`, implying that
    this object *must* be an instance of the nested type referred to by the
    stringified forward reference proxied by this fake proxy, implying:

    .. code-block:: python

       fake_proxy.__name__ == obj.__class__.__name__

    A contradiction! Ergo, this heuristic is guaranteed to *not* emit false
    positives. Quite Easily Done (QED). <-- *this is a lie*

    Parameters
    ----------
    hint_name : str
        Unqualified basename of the nested type to be proxied.
    scope_name : str
        Fully-qualified name of the lexical scope defining this nested type.

    Returns
    -------
    type[_BeartypeForwardRefFakeABC]
        Forward reference fake proxy pretending to proxy this nested type.
    '''

    # Forward reference fake proxy to be returned.
    fake_proxy = make_type(
        type_name=hint_name,
        #FIXME: Not *QUITE* right, but whatevahs. Close enough. Why? Because
        #this scope name could contain odd placeholders like ".<locals>."
        #preventing the resulting "type_module_name" from serving as a valid
        #Python identifier. The solution would be to strip the prefix of
        #"cls.__scope_name_beartype__" preceding the first ".<" substring in
        #this scope name. *WHATEVAHS*!
        type_module_name=scope_name,
        type_bases=_BeartypeForwardRefFakeABC_BASES,
    )

    # Return this fake proxy.
    return fake_proxy

# ....................{ PRIVATE ~ metaclasses              }....................
class _BeartypeForwardRefFakeMeta(type):
    '''
    Beartype **forward reference fake metaclass** (i.e., metaclass of the
    :class:`.BeartypeForwardRefFakeABC` abstract base class (ABC), whose
    concrete subclasses each pretend to resolve an otherwise unresolvable
    runtime-hostile forward reference through bald-faced trickery, casual
    deceit, and code prestidigitation the likes of which no living Pythonista
    could countenance).
    '''

    # ....................{ DUNDERS                        }....................
    @callable_cached
    def __repr__(cls: type['_BeartypeForwardRefFakeABC']) -> str:  # type: ignore[misc]
        '''
        Machine-readable string representing this forward reference fake proxy.

        This dunder method is memoized for efficiency.
        '''

        # Return the machine-readable representation of this fake proxy.
        #
        # Note that this representation is intentionally prefixed by the
        # @beartype-specific substring "<forwardreffake ", resembling the
        # representation of classes (e.g., "<class 'bool'>"). Why? Because
        # various other @beartype submodules ignore objects whose
        # representations are prefixed by the "<" character, which are usefully
        # treated as having a standard representation that is ignorable for most
        # intents and purposes. This includes:
        #   * The die_if_hint_pep604_inconsistent() raiser.
        return f'<forwardreffake {cls.__module__}.{cls.__name__}>'

    # ....................{ DUNDERS ~ pep : 3119           }....................
    def __instancecheck__(  # type: ignore[misc]
        fake_proxy: type['_BeartypeForwardRefFakeABC'], obj: object) -> bool:  # pyright: ignore
        '''
        :data:`True` only if the passed object superficially appears to be an
        instance of the **nested type** (i.e., low-level class whose declaration
        is confined to the body of a previously called higher-level callable and
        thus inaccessible to the current call stack lacking a stack frame
        encapsulating that prior call) referred to by the :pep:`484`-compliant
        stringified relative forward reference type hint proxied by the passed
        forward reference fake proxy.

        The :func:`isinstance` builtin implicitly calls this
        :pep:`3119`-compliant metaclass dunder method when passed a forward
        reference fake proxy as its second parameter.

        Parameters
        ----------
        fake_proxy : type['_BeartypeForwardRefFakeABC']
            Fake proxy to pretend to proxy this :func:`isinstance` check for.
        obj : object
            User-defined object to pretend to test this fake proxy against.
        '''

        # Return true only if the type of the passed user-defined object is a
        # subclass of the nested type referred to by the PEP 484-compliant
        # stringified relative forward reference type hint proxied by this
        # forward reference fake proxy, implying this object to be an instance
        # of that nested type.
        #
        # Note that this tester is memoized and thus requires that parameters be
        # only passed positionally.
        return _is_fake_proxy_superclass(fake_proxy, obj.__class__)


    def __subclasscheck__(  # type: ignore[misc]
        fake_proxy: type['_BeartypeForwardRefFakeABC'], subclass: type) -> bool:  # pyright: ignore
        '''
        :data:`True` only if the passed type superficially appears to be a
        subclass of the **nested type** (i.e., low-level class whose declaration
        is confined to the body of a previously called higher-level callable and
        thus inaccessible to the current call stack lacking a stack frame
        encapsulating that prior call) referred to by the :pep:`484`-compliant
        stringified relative forward reference type hint proxied by the passed
        forward reference fake proxy.

        The :func:`issubclass` builtin implicitly calls this
        :pep:`3119`-compliant metaclass dunder method when passed a forward
        reference fake proxy as its second parameter.

        Parameters
        ----------
        fake_proxy : type['_BeartypeForwardRefFakeABC']
            Fake proxy to pretend to proxy this :func:`issubclass` check for.
        subclass : object
            User-defined type to pretend to test this fake proxy against.

        Raises
        ------
        TypeError
            If this user-defined type is *not* actually a type.
        '''

        # Return true only if this user-defined type is a subclass of the nested
        # type referred to by the PEP 484-compliant stringified relative forward
        # reference type hint proxied by this forward reference fake proxy.
        #
        # Note that this tester is memoized and thus requires that parameters be
        # only passed positionally.
        return _is_fake_proxy_superclass(fake_proxy, subclass)

# ....................{ PRIVATE ~ superclasses             }....................
class _BeartypeForwardRefFakeABC(object, metaclass=_BeartypeForwardRefFakeMeta):
    '''
    Beartype **forward reference fake abstract base class (ABC)** (i.e.,
    superclass whose concrete subclasses each pretend to resolve an otherwise
    unresolvable runtime-hostile forward reference through bald-faced trickery,
    casual deceit, and code prestidigitation the likes of which no living
    Pythonista could countenance).
    '''

    pass

# ....................{ PRIVATE ~ testers                  }....................
@callable_cached
def _is_fake_proxy_superclass(
    fake_proxy: type[_BeartypeForwardRefFakeABC], subclass: type) -> bool:
    '''
    :data:`True` only if the passed **forward reference fake proxy** (i.e.,
    concrete :class:`._BeartypeForwardRefFakeABC` subclass created and returned
    by the public :func:`.proxy_type_fake` type factory) pretends to be a
    superclass of the passed user-defined class.

    This tester returns :data:`True` if and only if the unqualified basename of
    this fake proxy is that of at least one of the transitive superclasses in
    the method resolution order (MRO) of this user-defined class (including this
    user-defined class type itself).

    This tester is memoized for efficiency.

    Parameters
    ----------
    fake_proxy : type[_BeartypeForwardRefFakeABC]
        Forward reference fake proxy to test this subclass against.
    subclass : type
        User-defined type to be tested as a superclass of this fake proxy.

    Returns
    -------
    bool
        :data:`True` only if this fake proxy pretends to be a superclass of this
        user-defined class.

    Raises
    ------
    TypeError
        If this user-defined type is *not* actually a type.
    '''

    # Note that this test *CANNOT* be written as:
    #     isinstance(fake_proxy, _BeartypeForwardRefFakeABC)
    #
    # Why? Because doing so would ignite infinite recursion by implicitly
    # calling the _BeartypeForwardRefFakeMeta.__instancecheck__() dunder method,
    # which directly calls this lower-level tester. Metaclasses do be like that.
    # print(f'fake_proxy: {repr(fake_proxy}); class: {repr(fake_proxy.__class__)}')
    assert fake_proxy.__class__ is _BeartypeForwardRefFakeMeta, (
        f'{repr(fake_proxy)} not forward reference fake proxy.')

    # If this type is *NOT* a type, raise the standard "TypeError" exception
    # expected to be raised by the issubclass() builtin in this common edge
    # case. issubclass() implicitly calls the
    # _BeartypeForwardRefFakeMeta.__subclasscheck__() dunder method, which
    # directly calls this lower-level tester. To do so trivially, we
    # intentionally masquerade as the root "object" superclass.
    #
    # Weird Python is worky Python. Metaclasses do still be like that.
    issubclass(subclass, object)  # type: ignore[arg-type]

    # Unqualified basename of this fake proxy, localized purely as a negligible
    # microoptimization. It's best not to ask questions. You're thinking them,
    # though, aren't you!?
    fake_proxy_basename = fake_proxy.__name__

    # Return true only if...
    return any(
        # The unqualified basename of this fake proxy is that of this transitive
        # superclass...
        fake_proxy_basename == subclass_superclass.__name__
        # For each transitive superclass in the method resolution order (MRO) of
        # this other type (including this other type itself).
        for subclass_superclass in subclass.__mro__
    )

# ....................{ PRIVATE ~ tuples                   }....................
_BeartypeForwardRefFakeABC_BASES = (_BeartypeForwardRefFakeABC,)
'''
1-tuple containing *only* the :class:`._BeartypeForwardRefFakeABC` superclass to
reduce space and time consumption.
'''
