#!/usr/bin/env python3
# --------------------( LICENSE                            )--------------------
# Copyright (c) 2014-2026 Beartype authors.
# See "LICENSE" for further details.

'''
**Beartype decorator** :pep:`484` **type hint code generation** unit tests.

This submodule unit tests the :func:`beartype.beartype` decorator with respect
to :pep:`484`-specific type-checking code dynamically generated by the
:mod:`beartype._decor._nontype._wrap.wrapmain` submodule.
'''

# ....................{ IMPORTS                            }....................
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# WARNING: To raise human-readable test errors, avoid importing from
# package-specific submodules at module scope.
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
from beartype_test._util.mark.pytmark import ignore_warnings
from beartype_test._util.mark.pytskip import skip

# ....................{ TESTS ~ decorator                  }....................
# Prevent pytest from capturing and displaying all expected non-fatal
# beartype-specific warnings emitted by the @beartype decorator below. Urgh!
#FIXME: Remove when worky, obviously. *sigh*
#FIXME: Looks like user-defined generics are the current pain point. Our forward
#reference resolution mechanism is probably stripping their subscription and
#just reducing them to their raw type. Blah! Blah, we say!
#FIXME: *OH*. Right. Yeah. That's totally it. We were really trying to cut
#corners with this one:
#        # If this referent is a subscripted generic (e.g., "MuhGeneric[int]")...
#        if is_hint_pep484585_generic(referent):  # pyright: ignore
#            # Reduce this referent to the child type subscripting this generic
#            # (e.g., "int" in the prior example). Why? Because subscripted
#            # generics are neither isinstanceable *NOR* issubclassable: e.g.,
#            #     >>> MuhGeneric[T]: ...
#            #     >>> issubclass(type, MuhGeneric)
#            #     TypeError: issubclass() argument 2 cannot be a
#            #     parameterized generic
#            referent = get_hint_pep484585_generic_type(
#                hint=referent,  # pyright: ignore
#                exception_cls=BeartypeCallHintForwardRefException,
#                exception_prefix=cls.__exception_prefix_beartype__,
#            )
#
#            # Re-cache this referent under this preferable reduction.
#            _cache_ref_proxy_referent(cls=cls, referent=referent)
#        # Else, this referent is *NOT* a subscripted generic.
#
#That's demonstrably awful. Specifically, this part:
#            # Re-cache this referent under this preferable reduction.
#            _cache_ref_proxy_referent(cls=cls, referent=referent)
#
#What a double facepalm. Instead, we clearly need to:
#* Rename, for disambiguity:
#  * _cache_ref_proxy_referent() to _cache_ref_proxy_referent_hint().
#  * _uncache_ref_proxy_referent() to _uncache_ref_proxy_referent_hint().
#* Define a pair of new _cache_ref_proxy_referent_type() and
#  _uncache_ref_proxy_referent_type() functions.
#* *LOL*. "__resolved_type_beartype__" is totally busted. It should instead be:
#  * Locally defining a new "referent_type" local variable.
#  * Calling _cache_ref_proxy_referent_type() and
#    _uncache_ref_proxy_referent_type() (rather than
#    _cache_ref_proxy_referent_hint() and
#    _uncache_ref_proxy_referent_hint()).
#  * Unconditionally calling _cache_ref_proxy_referent_type() outside any "if"
#    statement or other block.

@skip('Currently brokey.')
@ignore_warnings(DeprecationWarning)
def test_beartype_pep484_ref_str(iter_hints_piths_meta) -> None:
    '''
    Test the :func:`beartype.beartype` decorator with respect to type-checking
    code dynamically generated by the
    :mod:`beartype._decor._nontype._wrap.wrapmain` submodule for
    :func:`beartype.beartype`-decorated callables annotated by one or more
    :pep:`484`-compliant stringified forward reference type hints referring to
    other arbitrary type hints supported by :mod:`beartype`.

    This is the core unit test validating decorator functionality from the end
    user perspective -- the only perspective that matters, in the end.
    Unsurprisingly, this test is mildly more involved than most. *Whatevah.*

    Parameters
    ----------
    iter_hints_piths_meta : Callable[[], Iterable[beartype_test.a00_unit.data.hint.metadata.pith.data_hintpithmeta.HintPithMetadata]]
        Factory function creating and returning a generator iteratively yielding
        ``HintPithMetadata`` instances, each describing a sample type hint
        exercising an edge case in the :mod:`beartype` codebase paired with a
        related object either satisfying or violating that hint.
    '''

    # ....................{ IMPORTS                        }....................
    # Defer test-specific imports.
    from beartype import beartype

    # ....................{ ASSERTS                        }....................
    # For each predefined type hint and associated metadata...
    for hint_pith_meta in iter_hints_piths_meta():
        # Metadata describing this hint.
        hint_meta = hint_pith_meta.hint_meta

        # Object to type-check against this hint.
        pith = hint_pith_meta.pith

        # Beartype decorator configured specifically for this hint.
        @beartype(conf=hint_meta.conf)
        def beartyped_func(arg: 'hint') -> 'hint':
            '''
            :func:`beartype.beartype`-decorated function both accepting a single
            parameter and returning a value annotated by a :pep:`484`-compliant
            stringified relative forward reference type hint referring to this
            hint, whose implementation reduces to the identity function.
            '''

            return arg

        # Type hint to be type-checked, intentionally localized *AFTER* defining
        # the above callable annotated by PEP 484-compliant stringified relative
        # forward reference type hints referring to this hint. If this hint were
        # instead define *BEFORE* defining that callable, the @beartype
        # decorator decorating that callable would simply resolve those relative
        # forward reference type hints at decoration time to this hint. Doing so
        # would prevent this unit test from validating any of the more esoteric
        # beartype machinery required to type-check references to arbitrary
        # non-type hints at late call time (rather than early decoration time).
        hint = hint_meta.hint

        # Assert that this function type-checks the pith associated with this
        # metadata against this hint as expected.
        with hint_pith_meta.beartyped_func_checking(beartyped_func):
            assert beartyped_func(pith) is pith

        # Prevent this hint from being erroneously resolved as the target
        # referent for the relative forward reference annotating the next
        # beartyped_func() defined by the next iteration. Look. It's complicate.
        del hint
