---
# --------------------( LICENSE                            )--------------------
# Copyright (c) 2014-2026 Beartype authors.
# See "LICENSE" for further details.
#
# --------------------( SYNOPSIS                           )--------------------
# GitHub-specific issue template, describing with human-readable language the
# process by which responsible end users submit security vulnerabilities as
# initially private GitHub-managed security advisories targeting this repository.

# ....................{ MAIN                               }....................
blank_issues_enabled: true

# ....................{ LINKS                              }....................
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/beartype/beartype/security/advisories/new
    about: >-
      Please do not open a public issue for security vulnerabilities.
      Report it privately here instead. Thank you so much! See our top-level
      "SECURITY.md" document for boring details.
