#!/usr/bin/env python3
# --------------------( LICENSE                            )--------------------
# Copyright (c) 2014-2026 Beartype authors.
# See "LICENSE" for further details.

'''
Beartype **type-checking expression lexical scope class hierarchy** (i.e.,
low-level dictionary subclasses mapping from the name to value of each attribute
referenced in the body of a pure-Python boolean expression type-checking an
arbitrary object against an arbitrary type hint).

This private submodule is *not* intended for importation by downstream callers.
'''

# ....................{ IMPORTS                            }....................
from beartype._cave._cavemap import NoneTypeOr
from beartype._check.forward.reference.fwdreftest import is_beartype_ref_proxy
from beartype._check.forward.reference.fwdreftyping import (
    TupleBeartypeForwardRefs)
from beartype._util.kind.maplike.utilmapfrozen import FrozenDictStrToAny
from typing import (
    TYPE_CHECKING,
    Optional,
)

# ....................{ SUBCLASSES                         }....................
#FIXME: Unit test us up, please.
class BeartypeCheckExprScope(FrozenDictStrToAny):
    '''
    Beartype **type-checking expression lexical scope** (i.e., immutable
    dictionary mapping from the name to value of each attribute referenced in
    the body of the pure-Python boolean expression type-checking an arbitrary
    object against an arbitrary type hint dynamically generated by the
    :func:`beartype._check.code.codemain.make_check_expr` code factory).

    Attributes
    ----------
    beartype_ref_proxies : tuple[BeartypeForwardRefMeta, ...]
        Tuple of all :mod:`beartype`-specific **forward reference proxies**
        (i.e., classes whose metaclass defers the resolution of forward
        reference type hints referencing type hints that have yet to be defined
        in the lexical scopes of external callers).
    is_check_expr_cacheable : bool
        :data:`True` only if callers may safely cache (memoize) this scope.
        Unsurprisingly, this boolean is an alias of the comparable
        :attr:`beartype._check.metadata.hint.hintsmeta.HintsMeta.is_check_expr_cacheable`
        boolean. See also that instance variable for further details.
    '''

    # ..................{ CLASS VARIABLES                    }..................
    # Slot all instance variables defined on this object to minimize the time
    # complexity of both reading and writing variables across frequently
    # called @beartype decorations. Slotting has been shown to reduce read and
    # write costs by approximately ~10%, which is non-trivial.
    __slots__ = (
        'beartype_ref_proxies',
        'is_check_expr_cacheable',
    )

    # Squelch false negatives from mypy. This is absurd. This is mypy. See:
    #     https://github.com/python/mypy/issues/5941
    if TYPE_CHECKING:
        beartype_ref_proxies: TupleBeartypeForwardRefs
        is_check_expr_cacheable: bool

    # ..................{ INITIALIZERS                       }..................
    def __init__(
        self,
        # Optional positional parameters.
        *args,

        # Optional keyword-only parameters.
        beartype_ref_proxies: Optional[TupleBeartypeForwardRefs] = None,
        is_check_expr_cacheable: bool = False,
        **kwargs
    ) -> None:
        '''
        Initialize this type-checking expression lexical scope with all passed
        parameters.

        This dictionary is initializable in the same manner as the builtin
        :meth:`dict.__init__` method. Since this dictionary is *not* mutatable
        after initialization, callers are strongly advised to pass one or more
        parameters to this constructor.

        Parameters
        ----------
        beartype_ref_proxies : tuple[BeartypeForwardRefMeta, ...], default: None
            Tuple of all :mod:`beartype`-specific **forward reference proxies**
            (i.e., classes whose metaclass defers the resolution of forward
            reference type hints referencing type hints that have yet to be
            defined in the lexical scopes of external callers). Defaults to
            :data:`None`, in which case this tuple is automatically introspected
            by iteration over the initial contents of this dictionary.
        is_check_expr_cacheable: bool, default: False
            :data:`True` only if callers may safely cache (memoize) this scope.
            Unsurprisingly, this boolean is an alias of the comparable
            :attr:`beartype._check.metadata.hint.hintsmeta.HintsMeta.is_check_expr_cacheable`
            boolean. Defaults to :data:`False` for safety.
        '''
        assert isinstance(beartype_ref_proxies, NoneTypeOr[tuple]), (
            f'{repr(beartype_ref_proxies)} neither tuple nor "None".')
        assert isinstance(is_check_expr_cacheable, bool), (
            f'{repr(is_check_expr_cacheable)} not boolean.')

        # Instantiate this scope with all passed parameters.
        super().__init__(*args, **kwargs)

        # If the caller failed to pass a tuple of all beartype-specific forward
        # reference proxies, introspect this tuple as the proper subset of all
        # attribute values accessed by this scope that are such proxies.
        if beartype_ref_proxies is None:
            self.beartype_ref_proxies = tuple(
                scope_value
                for scope_value in self.values()
                if is_beartype_ref_proxy(scope_value)
            )
        # Else, the caller passed such a tuple. In this case, reuse that tuple.
        else:
            self.beartype_ref_proxies = beartype_ref_proxies

        # Classify all remaining parameters.
        self.is_check_expr_cacheable = is_check_expr_cacheable

    # ..................{ REFREEZERS                         }..................
    def refreeze(self, *args, **kwargs) -> 'BeartypeCheckExprScope':
        '''
        New type-checking expression scope initialized both by the passed
        parameters in the same manner as the builtin :meth:`dict.__init__`
        method *and* by the same keyword-only parameters as originally passed to
        the :meth:`.__init__` method of this type-checking expression scope.

        This factory is typically called to freeze a mutable dictionary
        previously unfrozen from a prior instance of this immutable dictionary.
        This factory is syntactic sugar for manually instantiating new
        type-checking expression scopes from existing scopes ala:

        .. code-block:: python

           func_scope_refrozen = BeartypeCheckExprScope(
               func_scope,
               beartype_ref_proxies=func_scope_frozen.beartype_ref_proxies,
           )
        '''

        # Create and return a type-checking expression scope, initialized from
        # this scope *AND* the passed parameters.
        return BeartypeCheckExprScope(
            *args,
            # Reuse all previously computed instance variables bound to this
            # scope, for efficiency.
            beartype_ref_proxies=self.beartype_ref_proxies,
            is_check_expr_cacheable=self.is_check_expr_cacheable,
            **kwargs
        )
