#!/usr/bin/env python3
# --------------------( LICENSE                            )--------------------
# Copyright (c) 2014-2026 Beartype authors.
# See "LICENSE" for further details.

'''
Beartype **type-checking expression lexical scope class hierarchy** (i.e.,
low-level dictionary subclasses mapping from the name to value of each attribute
referenced in the body of a pure-Python boolean expression type-checking an
arbitrary object against an arbitrary type hint).

This private submodule is *not* intended for importation by downstream callers.
'''

# ....................{ IMPORTS                            }....................
from beartype._check.forward.reference.fwdreftest import is_beartype_ref_proxy
from beartype._check.forward.reference.fwdreftyping import (
    TupleBeartypeForwardRefs)
from beartype._util.kind.maplike.utilmapfrozen import FrozenDictStrToAny
from typing import TYPE_CHECKING

# ....................{ SUBCLASSES                         }....................
#FIXME: Unit test us up, please.
class BeartypeCheckExprScope(FrozenDictStrToAny):
    '''
    Beartype **type-checking expression lexical scope** (i.e., immutable
    dictionary mapping from the name to value of each attribute referenced in
    the body of the pure-Python boolean expression type-checking an arbitrary
    object against an arbitrary type hint dynamically generated by the
    :func:`beartype._check.code.codemain.make_check_expr` code factory).

    Attributes
    ----------
    beartype_ref_proxies : tuple[BeartypeForwardRefMeta, ...]
        Tuple of all :mod:`beartype`-specific **forward reference proxies**
        (i.e., classes whose metaclass defers the resolution of forward
        reference type hints referencing type hints that have yet to be defined
        in the lexical scopes of external callers).
    '''

    # ..................{ CLASS VARIABLES                    }..................
    # Slot all instance variables defined on this object to minimize the time
    # complexity of both reading and writing variables across frequently
    # called @beartype decorations. Slotting has been shown to reduce read and
    # write costs by approximately ~10%, which is non-trivial.
    __slots__ = (
        'beartype_ref_proxies',
    )

    # Squelch false negatives from mypy. This is absurd. This is mypy. See:
    #     https://github.com/python/mypy/issues/5941
    if TYPE_CHECKING:
        beartype_ref_proxies: TupleBeartypeForwardRefs

    # ..................{ INITIALIZERS                       }..................
    def __init__(self, *args, **kwargs) -> None:
        '''
        Initialize this type-checking expression lexical scope with all passed
        parameters.

        This dictionary is initializable in the same manner as the builtin
        :meth:`dict.__init__` method. Since this dictionary is *not* mutatable
        after initialization, callers are strongly advised to pass one or more
        parameters to this constructor.
        '''

        # Instantiate this scope with all passed parameters.
        super().__init__(*args, **kwargs)

        # Tuple of all beartype-specific forward reference proxies, efficiently
        # defined as the proper subset of all attribute values accessed by this
        # scope that are such proxies.
        self.beartype_ref_proxies = tuple(
            scope_value
            for scope_value in self.values()
            if is_beartype_ref_proxy(scope_value)
        )
