#!/usr/bin/env python3
# --------------------( LICENSE                            )--------------------
# Copyright (c) 2014-2026 Beartype authors.
# See "LICENSE" for further details.

'''
**Beartype type-checking function code factories** (i.e., low-level
callables dynamically generating pure-Python code snippets type-checking
arbitrary objects passed to arbitrary callables against PEP-compliant type hints
passed to those same callables).

This private submodule is *not* intended for importation by downstream callers.
'''

# ....................{ IMPORTS                            }....................
from beartype._cave._cavemap import NoneTypeOr
from beartype._check.code.codemain import (
    CodeGenerated,
    make_check_expr,
)
from beartype._check.error.errmain import (
    get_func_pith_violation,
    get_hint_object_violation,
)
from beartype._check.forward.reference.fwdrefset import (
    set_beartype_ref_proxies_exception_prefix)
from beartype._check.cls.call.calldataabc import BeartypeCallDataABC
from beartype._check.cls.call.calldatadecorfunc import (
    BeartypeCallDecorFuncData,
    prefix_decor_func_callable_pith,
)
from beartype._check.cls.hint.hintsane import HintSane
from beartype._conf.confmain import BeartypeConf
from beartype._data.check.code.datacodename import (
    ARG_NAME_CONF,
    ARG_NAME_EXCEPTION_PREFIX,
    ARG_NAME_GETRANDBITS,
    ARG_NAME_GET_VIOLATION,
    ARG_NAME_RAISER_HINT,
    ARG_NAME_WARN,
)
from beartype._data.check.code.func.datacodefunccheck import (
    CODE_GET_FUNC_PITH_VIOLATION,
    CODE_GET_HINT_OBJECT_VIOLATION,
    CODE_GET_VIOLATION_RANDOM_INT,
    CODE_RAISE_VIOLATION,
    CODE_RAISER_FUNC_PITH_CHECK_PREFIX,
    CODE_RAISER_HINT_OBJECT_CHECK_PREFIX,
    CODE_TESTER_CHECK_PREFIX,
    CODE_WARN_VIOLATION,
)
from beartype._data.func.datafuncarg import (
    ARG_NAME_RETURN,
    ARG_NAME_RETURN_REPR,
)
from beartype._data.typing.datatyping import LexicalScope
from beartype._data.typing.datatypingport import Hint
from beartype._util.cache.func.utilcachefunc import callable_cached
from beartype._util.hint.utilhintget import get_hint_repr
from beartype._util.kind.maplike.utilmapfrozen import (
    FrozenDict,
    FrozenDictStrToAny,
)
from itertools import count
from typing import Optional
from warnings import warn

# ....................{ CONSTANTS                          }....................
# Human-readable constants intended to be passed as the values of the
# "pith_kind" parameter accepted by the _make_code_raiser_violation() function
# factory. These values comprise a tri-state boolean. Since the higher-level
# make_code_raiser_func_pith_check() code factory accepts *ONLY* a strict
# (rather than tri-state) boolean, these constants are intentionally *NOT*
# defined as enumeration members.

PITH_KIND_FUNC_ARG = True
'''
Value of the ``pith_kind`` parameter accepted by the
:func:`._make_code_raiser_violation` function factory signifying the object
accepted by the type-checking raiser function created and returned by that
factory to be a **function parameter** (e.g., passed to a type-checking wrapper
function dynamically generated by the :func:`beartype.beartype` decorator).
'''


PITH_KIND_FUNC_RETURN = False
'''
Value of the ``pith_kind`` parameter accepted by the
:func:`._make_code_raiser_violation` function factory signifying the object
accepted by the type-checking raiser function created and returned by that
factory to be a **function return** (e.g., returned from a type-checking wrapper
function dynamically generated by the :func:`beartype.beartype` decorator).
'''


PITH_KIND_NONFUNC_OBJECT = None
'''
Value of the ``pith_kind`` parameter accepted by the
:func:`._make_code_raiser_violation` function factory signifying the object
accepted by the type-checking raiser function created and returned by that
factory to be an **arbitrary object** (e.g., passed to the
:func:`beartype.door.die_if_unbearable` raiser function).
'''

# ....................{ FACTORIES ~ code                   }....................
#FIXME: Unit test us up, please.
def make_code_raiser_hint_object_check(
    call_curr: BeartypeCallDataABC,
    hint_insane: Hint,
    hint_sane: HintSane,
    conf: BeartypeConf,
    exception_prefix: str,
) -> CodeGenerated:
    '''
    Pure-Python code snippet of a type-checking raiser function type-checking an
    arbitrary object against the passed type hint under the passed beartype
    configuration by either raising a fatal exception *or* emitting a non-fatal
    warning when that object violates this hint.

    This factory underlies the public :func:`beartype.door.die_if_unbearable`
    type-checking raiser function.

    This factory is intentionally *not* memoized (e.g., by the
    ``@callable_cached`` decorator), due to both accepting one or more
    unhashable parameters (e.g., ``call_curr``) *and* only being called by the
    higher-level memoized :func:`.make_func_checker` factory.

    Caveats
    -------
    **This low-level factory is only intended to be passed to the higher-level**
    :func:`.make_func_checker` **factory as the** ``make_code_check``
    **parameter.** This factory is *not* intended to be called directly.

    Parameters
    ----------
    call_curr : BeartypeCallDataABC
        **Beartype call metadata** (i.e., dataclass aggregating *all* common
        metadata encapsulating the lexical scope of the external call to the
        public :func:`beartype.door.die_if_unbearable` raiser function).
    hint_insane : Hint
        Possibly **insane** (i.e., pre-sanified) type hint to be type-checked.
    hint_sane : HintSane
        Metadata encapsulating the sanification of this type hint.
    conf : BeartypeConf
        **Beartype configuration** (i.e., self-caching dataclass encapsulating
        all settings configuring type-checking for the passed object).
    exception_prefix : str
        Human-readable substring prefixing raised exception messages.

    Returns
    -------
    CodeGenerated
        Tuple containing the Python code snippet dynamically generated by this
        code factory and metadata describing that code. See the
        :attr:`beartype._data.typing.datatyping.CodeGenerated` type hint.

    See Also
    --------
    :func:`.make_check_expr`
        Further details.
    '''

    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # CAUTION: Synchronize with the make_code_raiser_func_pith_check() factory.
    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    # ....................{ CHECKER                        }....................
    # Python code snippet comprising a single boolean expression type-checking
    # an arbitrary object against this hint.
    code_expr, func_scope_frozen = make_check_expr(
        call_curr=call_curr, hint_sane=hint_sane, conf=conf)

    # ....................{ SCOPE                          }....................
    # Mutable dictionary coerced from this immutable frozen dictionary.
    func_scope = dict(func_scope_frozen)

    # Pass hidden parameters to this raiser function exposing:
    # * The passed exception prefix accessed by this snippet.
    # * The get_hint_object_violation() getter called by the
    #   "CODE_GET_HINT_OBJECT_VIOLATION" snippet.
    # * The passed *INSANE* type hint accessed by this snippet. Why insane?
    #   Because the mere act of sanifying this hint typically reduces this hint
    #   from having a terse readable to verbose unreadable representation in
    #   violation messages raised by this raiser function. An insane hint is
    #   preferable for the purposes of generating readable violations.
    func_scope[ARG_NAME_EXCEPTION_PREFIX] = exception_prefix
    func_scope[ARG_NAME_GET_VIOLATION] = get_hint_object_violation
    func_scope[ARG_NAME_RAISER_HINT] = hint_insane

    # ....................{ RAISER                         }....................
    #FIXME: [SPEED] Globalize this bound method as a negligible efficiency gain.
    # Code snippet generating a human-readable violation exception or warning
    # when the root pith violates the root type hint.
    code_get_violation = CODE_GET_HINT_OBJECT_VIOLATION.format(
        arg_random_int=_get_func_scope_arg_random_int(func_scope))

    # Code snippet handling the previously generated violation by either raising
    # that violation as a fatal exception or emitting that violation as a
    # non-fatal warning.
    code_handle_violation = _make_code_raiser_violation(
        conf=conf, func_scope=func_scope)

    # ....................{ RETURN                         }....................
    # Code snippet type-checking the root pith against the root hint.
    func_code = (
        f'{CODE_RAISER_HINT_OBJECT_CHECK_PREFIX}'
        f'{code_expr}'
        f'{code_get_violation}'
        f'{code_handle_violation}'
    )

    # Type-checking expression lexical scope to be returned.
    func_scope_refrozen = func_scope_frozen.refreeze(func_scope)

    # Return all metadata required by higher-level callers.
    return (func_code, func_scope_refrozen)


#FIXME: Unit test us up, please.
def make_code_tester_check(
    call_curr: BeartypeCallDataABC,
    hint_insane: Hint,
    hint_sane: HintSane,
    conf: BeartypeConf,
    exception_prefix : str,
) -> CodeGenerated:
    '''
    Pure-Python code snippet of a type-checking tester function type-checking an
    arbitrary object against the passed type hint under the passed beartype
    configuration by returning whether that object satisfies this hint or not.

    This factory underlies the public :func:`beartype.door.is_bearable`
    type-checking tester function.

    This factory is intentionally *not* memoized (e.g., by the
    ``@callable_cached`` decorator), due to both accepting one or more
    unhashable parameters (e.g., ``call_curr``) *and* only being called by the
    higher-level memoized :func:`.make_func_checker` factory.

    Caveats
    -------
    **This low-level factory is only intended to be passed to the higher-level**
    :func:`.make_func_checker` **factory as the** ``make_code_check``
    **parameter.** This factory is *not* intended to be called directly.

    Parameters
    ----------
    call_curr : BeartypeCallDataABC
        **Beartype call metadata** (i.e., dataclass aggregating *all* common
        metadata encapsulating the lexical scope of the external call to the
        public :func:`beartype.door.is_bearable` tester function).
    hint_insane : Hint
        Possibly **insane** (i.e., pre-sanified) type hint to be type-checked.
    hint_sane : HintSane
        Metadata encapsulating the sanification of this type hint.
    conf : BeartypeConf
        **Beartype configuration** (i.e., self-caching dataclass encapsulating
        all settings configuring type-checking for the passed object).
    exception_prefix : str
        Human-readable substring prefixing raised exception messages.

    Returns
    -------
    CodeGenerated
        Tuple containing the Python code snippet dynamically generated by this
        code factory and metadata describing that code. See the
        :attr:`beartype._data.typing.datatyping.CodeGenerated` type hint.

    See Also
    --------
    :func:`.make_check_expr`
        Further details.
    '''

    # Python code snippet comprising a single boolean expression type-checking
    # an arbitrary object against this hint.
    code_expr, func_scope_frozen = make_check_expr(
        call_curr=call_curr, hint_sane=hint_sane, conf=conf)

    # Code snippet type-checking the root pith against the root hint.
    func_code = f'{CODE_TESTER_CHECK_PREFIX}{code_expr}'

    # Return all metadata required by higher-level callers.
    return (func_code, func_scope_frozen)

# ....................{ FACTORIES ~ code : raiser          }....................
#FIXME: Pretty sure *ALL* factories (including this factory) should return a
#full-blown "CodeGenerated" 2-tuple rather than the hacky
#"tuple[str, FrozenDictStrToAny]" we're currently returning. Oh, well. The
#current approach works, technically. It's just non-orthogonal and weird. *sigh*
@callable_cached
def make_code_raiser_func_pep484_noreturn_check(
    conf: BeartypeConf) -> tuple[str, FrozenDictStrToAny]:
    '''
    Pure-Python code snippet of a type-checking raiser function type-checking a
    return of a decorated callable against the :obj:`typing.NoReturn` type hint
    annotating that return under the passed beartype configuration by either
    raising a fatal exception *or* emitting a non-fatal warning when that
    callable violates this hint by itself failing to raise an exception.

    This factory is memoized for efficiency.

    Parameters
    ----------
    conf : BeartypeConf
        **Beartype configuration** (i.e., self-caching dataclass encapsulating
        all settings configuring type-checking for the passed object).

    Returns
    -------
    tuple[str, FrozenDictStrToAny]
        Tuple containing the Python code snippet dynamically generated by this
        code factory and metadata describing that code. See also the
        :attr:`beartype._data.typing.datatyping.CodeGenerated` type hint.
    '''

    # Lexical scope to be returned, initialized to the empty dictionary.
    func_scope: LexicalScope = {}

    # Pass hidden parameters to this raiser function exposing the
    # get_func_pith_violation() getter called by the
    # "CODE_GET_FUNC_PITH_VIOLATION" snippet.
    func_scope[ARG_NAME_GET_VIOLATION] = get_func_pith_violation

    #FIXME: [SPEED] Globalize CODE_GET_FUNC_PITH_VIOLATION_format(), please.
    # Code snippet generating a human-readable violation exception or warning
    # when the root pith violates the root type hint.
    code_get_violation = CODE_GET_FUNC_PITH_VIOLATION.format(
        arg_random_int='', pith_name=ARG_NAME_RETURN_REPR)

    # Code snippet handling the previously generated violation by either raising
    # that violation as a fatal exception *OR* emitting that violation as a
    # non-fatal warning.
    code_handle_violation = _make_code_raiser_violation(
        conf=conf, func_scope=func_scope, pith_kind=PITH_KIND_FUNC_RETURN)

    # Code snippet type-checking the root pith against the root hint.
    func_code = f'{code_get_violation}{code_handle_violation}'

    # Coerce this currently mutable non-frozen dictionary into an immutable
    # frozen dictionary, preventing callers from erroneously modifying this
    # frozen dictionary when memoized below and subsequently returned to
    # different callers. Freezing this dictionary slightly reduces efficiency
    # (which is slightly bad) but *DRAMATICALLY* eliminates otherwise impossible
    # to debug memoization issues. Debugging wins! \o/
    func_scope_frozen: FrozenDictStrToAny = FrozenDict(func_scope)

    # Return all metadata required by higher-level callers.
    return (func_code, func_scope_frozen)

# ....................{ FACTORIES ~ code : raiser : pith   }....................
#FIXME: Unit test us up, please.
#FIXME: [SPEED] This factory could (and should) be contextually memoized in a
#similar manner to that of the lower-level make_check_expr() factory internally
#called by this higher-level factory. That is exactly what the comparable
#make_func_checker() factory now does, in fact! See the latter for details.
def make_code_raiser_func_pith_check(
    decor_func: BeartypeCallDecorFuncData,
    hint_sane: HintSane,
    pith_name: str,
) -> CodeGenerated:
    '''
    Pure-Python code snippet of a type-checking raiser function type-checking a
    parameter or return of a decorated callable against the passed type hint
    under the passed beartype configuration by either raising a fatal exception
    *or* emitting a non-fatal warning when that parameter or return violates
    this hint.

    This factory is intentionally *not* memoized (e.g., by the
    ``@callable_cached`` decorator), due to accepting one or more unhashable
    parameters (e.g., ``decor_func``).

    Parameters
    ----------
    decor_func : BeartypeCallDecorFuncData
        **Beartype decorator call metadata** (i.e., dataclass aggregating *all*
        metadata encapsulating the currently decorated callable).
    hint_sane : HintSane
        Metadata encapsulating the sanification of the hint to be type-checked.
    pith_name : str
        Name of the parameter or return value of this callable to be labelled.

    Returns
    -------
    CodeGenerated
        Tuple containing the Python code snippet dynamically generated by this
        code factory and metadata describing that code. See the
        :attr:`beartype._data.typing.datatyping.CodeGenerated` type hint.

    See Also
    --------
    :func:`.make_check_expr`
        Further details.
    '''
    assert isinstance(decor_func, BeartypeCallDecorFuncData), (
        f'{repr(decor_func)} not beartype decorator call metadata.')
    assert isinstance(pith_name, str), f'{repr(pith_name)} not string.'

    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # CAUTION: Synchronize with make_code_raiser_hint_object_check().
    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    # ....................{ CODE                           }....................
    # Python code snippet comprising a single boolean expression type-checking
    # an arbitrary object against this hint.
    code_expr, func_scope_frozen = make_check_expr(
        call_curr=decor_func, hint_sane=hint_sane, conf=decor_func.conf)

    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # CAUTION: Synchronize with similar logic in make_func_checker() above.
    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # If the decorated callable is annotated by one or more forward references
    # *NOT* resolvable at decoration time, these references have all been
    # proxied by beartype-specific forward reference proxies. In this case...
    if func_scope_frozen.beartype_ref_proxies:
        # Overwrite the default value of the "__exception_prefix_beartype__"
        # class variables bound to these proxies with a specific exception
        # prefix contextually describing the currently decorated callable,
        # dramatically improving the readability of exceptions raised at
        # type-checking wrapper call time if one of these proxies fails to
        # resolve the reference it proxies.
        #
        # Note that constructing this prefix is computationally expensive and
        # thus deferred until absolutely confirmed to be needed [read: *NOW*].
        set_beartype_ref_proxies_exception_prefix(
            ref_proxies=func_scope_frozen.beartype_ref_proxies,
            exception_prefix=prefix_decor_func_callable_pith(
                decor_func=decor_func, pith_name=pith_name),
        )
    # Else, the decorated callable is annotated by *NO* such references.

    # ....................{ SCOPE                          }....................
    # Mutable dictionary coerced from this immutable frozen dictionary.
    func_scope = dict(func_scope_frozen)

    # Expose the get_func_pith_violation() getter called by the
    # "CODE_GET_FUNC_PITH_VIOLATION" snippet as a "beartype"-specific hidden
    # parameter passed to this wrapper function.
    func_scope[ARG_NAME_GET_VIOLATION] = get_func_pith_violation

    # ....................{ RAISER                         }....................
    #FIXME: [SPEED] Globalize CODE_GET_FUNC_PITH_VIOLATION.format() as
    #"CODE_GET_FUNC_PITH_VIOLATION_format". *sigh*
    # Code snippet generating a human-readable violation exception or warning
    # when the root pith violates the root type hint.
    code_get_violation = CODE_GET_FUNC_PITH_VIOLATION.format(
        arg_random_int=_get_func_scope_arg_random_int(func_scope),
        pith_name=get_hint_repr(pith_name),
    )

    # Code snippet handling the previously generated violation by either raising
    # that violation as a fatal exception or emitting that violation as a
    # non-fatal warning.
    code_handle_violation = _make_code_raiser_violation(
        conf=decor_func.conf,
        func_scope=func_scope,

        #FIXME: *SUPER-SILLY*. This can be trivially deduced from the passed
        #"pith_name". Clearly, this is an ancient vestigial artifact of an era
        #in which we tried *REALLY* hard to unconditionally cache this factory.
        #Naturally, that was a catastrophic failure. Since this parameter no
        #longer has a reason to live, excise us up, please. *sigh*
        pith_kind=(
            PITH_KIND_FUNC_RETURN
            if pith_name is ARG_NAME_RETURN else
            PITH_KIND_FUNC_ARG
        ),
    )

    # ....................{ RETURN                         }....................
    # Code snippet type-checking the root pith against the root hint.
    func_code = (
        f'{CODE_RAISER_FUNC_PITH_CHECK_PREFIX}'
        f'{code_expr}'
        f'{code_get_violation}'
        f'{code_handle_violation}'
    )

    # Type-checking expression lexical scope to be returned.
    func_scope_refrozen = func_scope_frozen.refreeze(func_scope)

    # Return all metadata required by higher-level callers.
    return (func_code, func_scope_refrozen)

# ....................{ PRIVATE ~ globals                  }....................
_func_checker_name_counter = count(start=0, step=1)
'''
**Type-checking function name uniquifier** (i.e., iterator yielding the next
integer incrementation starting at 0, leveraged by the
:func:`.make_func_checker` factory to uniquify the names of the type-checking
functions dynamically generated by that factory).
'''

# ....................{ PRIVATE ~ testers                  }....................
def _func_checker_ignorable(obj: object) -> bool:
    '''
    **Ignorable type-checking tester function singleton** (i.e., function
    unconditionally returning :data:`True`, semantically equivalent to a tester
    testing whether an arbitrary object passed to this tester satisfies an
    ignorable type hint).

    The :func:`make_func_tester` factory efficiently returns this singleton when
    passed an ignorable type hint rather than inefficiently regenerating a
    unique ignorable type-checking tester function for that hint.
    '''

    return True

# ....................{ PRIVATE ~ getters                  }....................
#FIXME: Unit test us up, please.
def _get_func_scope_arg_random_int(func_scope: LexicalScope) -> str:
    '''
    Code snippet intended to be embedded as the ``arg_random_int`` format
    variable of either the parent :data:`.CODE_GET_HINT_OBJECT_VIOLATION` or
    :data:`.CODE_GET_FUNC_PITH_VIOLATION` code snippets.

    Parameters
    ----------
    func_scope : LexicalScope
        **Lexical scope** (i.e., dictionary mapping from the relative
        unqualified name to value of each locally or globally scoped attribute
        accessible to a callable or class).

    Returns
    -------
    str
        Either:

        * If the passed lexical scope accepts a random integer generator, a code
          snippet passing the value of the random integer previously generated
          by that generator for the current call of a high-level type-checking
          function to a call as a keyword parameter to a lower-level
          type-checking exception raiser function call.
        * Else, the empty string.
    '''
    assert isinstance(func_scope, dict), f'{repr(func_scope)} not dictionary.'

    # Return either...
    return (
        # If this lexical scope accepts a random integer generator, the code
        # snippet described above;
        CODE_GET_VIOLATION_RANDOM_INT
        if ARG_NAME_GETRANDBITS in func_scope else
        # Else, the empty string.
        ''
    )

# ....................{ PRIVATE ~ factories : code         }....................
def _make_code_raiser_violation(
    # Mandatory parameters.
    conf: BeartypeConf,
    func_scope: LexicalScope,

    # Optional parameters.
    pith_kind: Optional[bool] = PITH_KIND_NONFUNC_OBJECT,
) -> str:
    '''
    Pure-Python code snippet of a **type-checking raiser function** (i.e.,
    dynamically generated by the :func:`.make_raiser_func` factory) either
    raising a fatal exception or emitting a non-fatal warning when an arbitrary
    object violates an arbitrary type hint under the passed beartype
    configuration in the body of that raiser.

    This factory is intentionally *not* memoized (e.g., by the
    ``@callable_cached`` decorator), as this factory is only called by
    higher-level memoized factories.

    Parameters
    ----------
    conf : BeartypeConf
        **Beartype configuration** (i.e., self-caching dataclass encapsulating
        all settings configuring type-checking for the passed object).
    func_scope : LexicalScope
        **Lexical scope** (i.e., dictionary mapping from the relative
        unqualified name to value of each locally or globally scoped attribute
        accessible to a callable or class).
    pith_kind : Optional[bool], default: PITH_KIND_NONFUNC_OBJECT
        **Tri-state pith boolean.** Although it would be simpler for this
        factory to accept a pith name, doing so would effectively unmemoize all
        higher-level memoized factories calling this code factory. If the code
        snippet generated and returned by this code factory type-checks a
        previously localized:

        * Parameter of a decorated callable, :data:`.PITH_KIND_FUNC_ARG`.
        * Return of a decorated callable, :data:`.PITH_KIND_FUNC_RETURN`.
        * Arbitrary object passed to the parent
          :func:`beartype.door.die_if_uncallable` type-checker,
          :data:`.PITH_KIND_NONFUNC_OBJECT`.

        Defaults to :data:`.PITH_KIND_NONFUNC_OBJECT` for both simplicity and
        readability.

    Returns
    -------
    CodeGenerated
        Tuple containing the Python code snippet dynamically generated by this
        code factory and metadata describing that code. See the
        :attr:`beartype._data.typing.datatyping.CodeGenerated` type hint for
        details.

    Raises
    ------
    All exceptions raised by the lower-level :func:`.make_check_expr` factory.

    Warns
    -----
    All warnings emitted by the lower-level :func:`.make_check_expr` factory.

    See Also
    --------
    :func:`.make_check_expr`
        Further details.
    '''
    assert isinstance(conf, BeartypeConf), f'{repr(conf)} not configuration.'
    assert isinstance(func_scope, dict), f'{repr(func_scope)} not dictionary.'
    assert isinstance(pith_kind, NoneTypeOr[bool]), (
        f'{repr(pith_kind)} neither boolean nor "None".')

    # Pass a hidden parameter to this raiser function exposing the passed
    # beartype configuration accessed by this snippet.
    func_scope[ARG_NAME_CONF] = conf

    # Code snippet handling the previously generated violation by either raising
    # that violation as a fatal exception or emitting that violation as a
    # non-fatal warning, contextually initialized below.
    code_violation = ''  # type: ignore[assignment]

    # If this code snippet produces this violation by emitting a non-fatal
    # warning (rather than raising an exception), detected as either...
    if (
        # If this object is neither a parameter nor return of a decorated
        # callable, this object was directly passed to either the
        # beartype.door.is_bearable() or beartype.door.die_if_unbearable()
        # functions. In either case, set this boolean to this previously
        # computed DOOR-specific boolean.
        conf._is_violation_door_warn
        if pith_kind is PITH_KIND_NONFUNC_OBJECT else
        # Else, this object is either a parameter or return of a decorated
        # callable.
        #
        # If this object is be a parameter of a decorated callable, set this
        # boolean to this previously computed parameter-specific boolean.
        conf._is_violation_param_warn
        if pith_kind is PITH_KIND_FUNC_ARG else
        # Else, this object is *NOT* a parameter of a decorated callable. In this
        # case, this object *MUST* be a return of a decorated callable. Set
        # this boolean to this previously computed return-specific boolean.
        conf._is_violation_return_warn
    ):
        # Emit a non-fatal warning.
        code_violation = CODE_WARN_VIOLATION

        # Pass the warnings.warn() function required to emit this warning to
        # this wrapper function as an optional hidden parameter.
        #
        # Note that we intentionally do *NOT* pass the higher-level
        # issue_warning() function. Why? Efficiency, mostly. Recall that
        # issue_warning() is *ONLY* called to pretend that warnings generated by
        # callables both defined by and residing in this codebase are actually
        # generated by external third-party code. Although this wrapper function
        # is also generated by callables defined by this codebase (including
        # this callable, of course), this wrapper function does *NOT* reside
        # inside this codebase but instead effectively resides inside the
        # external third-party module defining the original function this
        # wrapper function wraps. Needlessly passing issue_warning() rather than
        # warn() here would only consume CPU cycles for *NO* tangible gain.
        func_scope[ARG_NAME_WARN] = warn
    # Else, raise a fatal exception.
    else:
        code_violation = CODE_RAISE_VIOLATION

    # Return this code snippet.
    return code_violation
